permalink: /:categories/:year/:month/:day/:title 

include: ["css","images"]
exclude: [".rvmrc", ".ruby-version", "README.md", "Rakefile", "changelog.md", "vendor"]

highlighter: rouge

title : zil
tagline: Writing Matters
author :
  name : zil
  email : fantanstic@gmail.com
  github : zil
  feedburner: zil

archive_path: /archive.html
pages_path : /pages.html
categories_path : /categories.html
tags_path : /tags.html
about_path : /about.html

comments :
  provider : duoshuo
